google/fscrypt

Makefile
README.md

This PR changes how versioning works in fscrypt. Now [releases will be make of fscrypt](https://github.com/google/fscrypt/releases) and the tags from those releases will generate the version displayed with `fscrypt --version` and in the badge at the top of the README.
Fixes #6

Version now uses git tags and releases

---

actions/policy.go
crypto/crypto_test.go
crypto/key.go

Before we were using the to place keys in the keying. This is resulted in many instances of `service + descriptor` in the code. Now a policy has a `Description()` indicating the name of it's policy key when in the keyring.

Use Description when placing keys in the keyring

---

cmd/fscrypt/commands.go
cmd/fscrypt/status.go
filesystem/filesystem.go

Previously, fscrypt conflated the ideas of metadata existence (`/.fscrypt` directories) and encryption support (supporting the kernel IOCTLs). This PR separates them. Now filesystems can have metadata if they do not support encryption, and `fscrypt status` is improved with additional data.

Separate encryption support from metadata support

---

cmd/fscrypt/errors.go
cmd/fscrypt/keys.go
cmd/fscrypt/prompt.go
crypto/key.go
pam/constants.go
pam/login.go
pam/pam.c
pam/pam.go
pam/pam.h
util/util.go
util/util_test.go

This PR significantly updates the PAM package so we will be able to build our PAM module (see #4).
Specifically, this includes:
- Changing the `Key` struct to support creation from/to C strings
- Changing the `util` package to support more array conversions
- Changing the `pam` package to have significantly more features (using [this package](https://github.com/msteinert/pam))
- Changing `cmd/fscrypt` to support the new API
- Refactoring how unknown UIDs are handled.

Add PAM package

---

.travis.yml
CONTRIBUTING.md
Makefile
README.md
crypto/crypto_test.go

Attempting to use [coveralls](https://coveralls.io/) and [goveralls](https://github.com/mattn/goveralls) to setup automated test coverage metrics

coveralls: Adding Travis CI integration

---

README.md

Closes #28 
The current `go get -d` instructions will show a warning because the top level directory contains no Go code. Using `go set -d github.com/google/fscrypt/...` solves this problem while still checking out the `README.md`, `Makefile`, and other documents in the root directory.

Fixed cloning instructions

---

README.md

The version badge was broken. This fixes it and inlines the version in the top line.

README reformatting

---

cmd/fscrypt/errors.go

The key file for the raw_key source is required to contain a wrapping
key (32 bytes), not a policy key (64 bytes).

cmd/fscrypt: fix help message for ErrKeyFileLength

---

actions/config.go

'fscrypt setup' is supposed to calibrate the Argon2 password hashing
difficulty to 1s by default, but actually it was setting it to only 1s /
num_cpus because the hashing is done with all CPUs and it is timed using
the CLOCK_PROCESS_CPUTIME_ID clock, which measures the time spent by all
threads in the process.  Fix this by dividing the elapsed time by
HashingCosts.Parallelism, which is used as the number of threads.

actions: calculate password hash difficulty correctly

---

util/util.go

Fixes #31 
For the pointer to slice conversion functions to work on a 32-bit architecture, the slices must not have a size that exceeds `MatInt32`. This PR increases the allowable size for the byte slices, while making sure that the pointer slices will build on 32-bit.
Unfortunately, Travis CI does not support non x86_64 builds (see: https://github.com/travis-ci/travis-ci/issues/986), so testing this will have to be done manually.

util: Slice/Pointer conversion fits in MatInt32

---

actions/policy.go
crypto/crypto.go
crypto/key.go

Fixes #34 
This commit moves from the session keyring to the user keyring. This change also allows us to eliminate `getKeyring()` as the user keyring does not have the problems of the session keyring. There is also a small API change as we no longer need to pass along the session keyring id.

crypto: Switch from session to user keyring

---

actions/context.go
actions/policy.go
cmd/fscrypt/commands.go
cmd/fscrypt/errors.go
cmd/fscrypt/flags.go
cmd/fscrypt/fscrypt.go
crypto/crypto.go
crypto/crypto_test.go
crypto/key.go
pam/pam.go
security/keyring.go
security/privileges.go
util/util.go

Fixes #35 
This PR also does some general cleanup by separating things like privilege dropping and keyring management to a separate `security` package. 
As part of this cleanup,  the `(Drop/Raise)ThreadPrivileges` functions are added. These also serve to make sure the correct keyrings are linked. These will also be used with the PAM module (see #4)

Purge command now clears cache

---

.gitignore
CONTRIBUTING.md
Makefile
README.md
actions/policy.go
cmd/fscrypt/commands.go
crypto/key.go
pam/login.go
pam/pam.go
pam_fscrypt/config
pam_fscrypt/pam_fscrypt.go
pam_fscrypt/run_fscrypt.go
security/cache.go
security/keyring.go
security/privileges.go
util/util.go

This commit closes #4 by adding in `pam_fscrypt`. See the updated documentation for more information.

fscrypt PAM module

---

.travis.yml
Makefile
README.md
filesystem/filesystem.go
filesystem/mountpoint.go

This fixes #50 which showed how the libblkid cache is sometimes missing certain entries, making it impossible to create a filesystem link for an unprivileged user.
This PR removes the entire dependency on `libblkid` and `libuuid`. Now, a search of `/dev/disk/by-uuid` is done to find the appropriate UUID. This takes a dependency on certain _default_ udev configs, but only for creating filesystem links. The rest of fscrypt will work without the dependency.

Use `/dev/disk/by-uuid` to get UUID links to other filesystems 

---

actions/policy.go
cmd/fscrypt/commands.go
cmd/fscrypt/errors.go
cmd/fscrypt/flags.go
pam/pam.go
pam_fscrypt/run_fscrypt.go
security/keyring.go
security/privileges.go

This PR stops certain functionality from failing in the PAM module. This is mainly done by changing how we lookup the user keyring. We no longer user goroutines, which were part of the problem.
The PAM functions are now (mostly) insulated against panics making them crash. This fixes #53

Fixed failures in PAM module

---

cmd/fscrypt/flags.go
pam/pam.go
security/keyring.go

This means the "user keyring in session keyring" invariant will not be checked when searching for or removing a key. 
Fixes #57 (hopefully)

security: Add check option to UserKeyringID

---

cmd/fscrypt/commands.go
cmd/fscrypt/flags.go
pam_fscrypt/pam_fscrypt.go
security/cache.go

This PR addresses some of the issues in #66 by `sync()`ing the filesystem before dropping the caches. The documentation and comments are updated as well to clarify the functionality and indicate the limits of this action.

security: Sync filesystem before dropping caches

---

Makefile
input_fail.py

Some minor cleanup of `Makefile` and related scripts. `make test` now runs in Travis CI.

Makefile cleanup

---

actions/config.go

Fixes #73.
Adds maxMemoryBytes as 128MiB and cleans up the helper
functions/variables to make it more clear which values are a number of
bytes, and which values are a number of KiB.

Limit the amount of RAM that will be used

---

actions/protector.go
cmd/fscrypt/commands.go
cmd/fscrypt/strings.go
crypto/key.go
metadata/policy.go
pam/pam.go
pam_fscrypt/run_fscrypt.go

Fixes an issue where if fscrypt was built with `go build github.com/google/fscrypt/cmd/fscrypt`, the `Compiled:` line in `fscrypt --version` would still appear (as the zero value for a date is still a valid date).
This also uses `go vet -shadow ./...` to find cases where we are using shadowing incorrectly. It still gives some false positives, but it did find a few problems.

Minor fixes and cleanup

---

pam/pam.go

pam_fscrypt is crashing with a segfault in copyIntoSecret() when using
Ctrl-C to interrupt a 'sudo' prompt.  It is dereferencing a NULL pointer
that is supposed point to the PAM_AUTHTOK item.  The problem is that the
Go code assumes pam_get_item() returns a non-success status if the item
is unset, when actually it sets the data pointer to NULL and returns
PAM_SUCCESS.
Fix it by making pam.Handle.GetItem() return an error in that case.

pam: return error when PAM info item is unset

---

pam/pam.go
security/privileges.go

After enabling pam_fscrypt for "session" and creating a directory
protected with a login protector, I was no longer able to log in as that
user.  The problem is that the Go runtime is creating threads after
pam_fscrypt drops privileges, but pam_fscrypt is not re-acquiring
privileges on those threads because the Go wrappers for setreuid(),
setregid(), and setgroups() in the "sys/unix" package are using the raw
syscalls which operate on the calling thread only.
This violates glibc's assumption that all threads have the same uids and
gids, causing it to abort() the process when a later module in the PAM
stack (pam_mail in my case) tries to drop privileges using the glibc
functions.
Fix it by dropping and regaining privileges using the glibc functions
rather than the "sys/unix" functions. …

security: drop and regain privileges in all threads

---

util/util.go

Addresses most of the issues in #101.
The following commands now succeed:
GOARCH=mips go build github.com/google/fscrypt/util
GOARCH=mipsle go build github.com/google/fscrypt/util

Use proper sizes when casting to Go slice

---

.travis.yml
README.md

We want to use some of the `cgo` improvements in 1.10 that will simplify our code.

Fix Travis to only use Go 1.10

---

pam/pam.go
pam_fscrypt/pam_fscrypt.go
pam_fscrypt/run_fscrypt.go
security/keyring.go
security/privileges.go

Fixes #77 and [CVE-2018-6558](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-6558)
This PR changes how privilege dropping/raising is done throughout fscrypt.  It makes sure that all changes are exactly reversed to prevent issues where user's would have their group membership messed up after login. This lead to a security issue where users could end up a member of the `root` group (GID=0), resulting in privilege escalation.

Cleanup privilege dropping/raising in pam_fscrypt

---

Makefile

'make gen' no longer works because it uses the git version of
protoc-gen-go, which is no longer compatible with the latest released
version of github.com/golang/protobuf/proto, which we're using.  Freeze
the protoc-gen-go version so that it keeps working.

Makefile: use a specific protoc-gen-go version

---

.gitignore
CONTRIBUTING.md
Makefile

This fixes Travis issues as well as moving us off of deprecated tooling

Makefile: migrate from megacheck to staticcheck

---

.gitignore
Makefile
README.md
pam_fscrypt/config

Per the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), manually installed programs should go under `/usr/local`.
This change also makes it easier to change the global installation
prefix. For example, package managers should set `PREFIX=/usr`

Install pam modules/configs to the right location

---

Makefile
filesystem/mountpoint.go

* Exclude generated files from 'make format'
* Run 'make format' with latest version of goimports

Fix 'make format'-related CI failure

---

.gitignore

Add the tags file to .gitignore, for developers using
https://github.com/jstemmer/gotags.

.gitignore: add tags file

---

actions/policy.go
cmd/fscrypt/status.go

Show the encryption options when running 'fscrypt status' on a
directory.  E.g.:
Policy:   490515286453d3f7
Options:  padding:32 contents:Adiantum filenames:Adiantum
Unlocked: Yes

cmd/fscrypt: show encryption options with 'fscrypt status DIR'

---

README.md
cmd/fscrypt/commands.go
cmd/fscrypt/setup.go

Make the global setup command also create the metadata directory at
/.fscrypt, since that's where login protectors are placed, even when the
actual encrypted directories are on a different filesystem.
Resolves https://github.com/google/fscrypt/issues/129

cmd/fscrypt: make 'fscrypt setup' create /.fscrypt

---

filesystem/filesystem.go
filesystem/filesystem_test.go
filesystem/path.go

Support the case where the user has a read-only root filesystem (e.g.
with OSTree) and had previously created a symlink /.fscrypt pointing to
a writable location, so that login protectors can be created there.
Resolves https://github.com/google/fscrypt/issues/131

filesystem: allow .fscrypt to be a symlink

---

actions/config.go
actions/config_test.go
filesystem/path.go

If the user has set a restrictive umask, e.g. 0077, then
/etc/fscrypt.conf would be created without the world-readable bit set.
Fix it by overriding the umask when creating the file.
Resolves https://github.com/google/fscrypt/issues/151

actions/config: ensure config file is created with mode 0644

---

actions/context.go
cmd/fscrypt/status.go
filesystem/filesystem.go
filesystem/mountpoint.go
filesystem/mountpoint_test.go
filesystem/path.go
filesystem/path_test.go

Store fscrypt metadata in only one place per filesystem, so that bind mounts don't get their own metadata directories (which was ambiguous, as the same file may be accessible via multiple mounts).
Also correctly set the source device for root filesystems mounted via the kernel command line, and fix creating linked protectors to such filesystems.
See the commit messages for details.

Handle bind mounts correctly, and other mount-related improvements

---

.travis.yml

Ensure that the environmental variable GO111MODULE is set to "on" when
running 'go get'.  This fixes a CI failure with Go 1.11 and 1.12.

travis: set GO111MODULE=on for 'go get'

---

filesystem/mountpoint.go
filesystem/mountpoint_test.go

To make manually editing linked protectors slightly more user-friendly,
automatically strip any leading or trailing whitespace.  E.g. treat
"UUID=3a6d9a76-47f0-4f13-81bf-3332fbe984fb\n" the same as
"UUID=3a6d9a76-47f0-4f13-81bf-3332fbe984fb".
Update https://github.com/google/fscrypt/issues/115

Allow filesystem links to contain leading/trailing whitespace

---

README.md
cmd/fscrypt/prompt.go

Saying "Your data can be protected with one of the following sources" is
ambiguous because it could be interpreted to mean that an encrypted
directory can only have one type of protector.  In fact, an encrypted
directory can have multiple protectors, and they can be of any type.
Update https://github.com/google/fscrypt/issues/164

cmd/fscrypt: adjust message when listing protector sources

---

actions/context.go
crypto/crypto_test.go
go.mod
go.sum
metadata/constants.go
metadata/metadata.pb.go
metadata/metadata.proto
metadata/policy.go

* Upgrade sys module to get the new fscrypt declarations from Linux v5.4.
* Use the new name for fscrypt constants and structures which have been given a new name.

Upgrade to latest golang.org/x/sys module

---

actions/context.go
cmd/fscrypt/commands.go
cmd/fscrypt/flags.go
crypto/key.go
security/keyring.go

Refer to the target User as 'targetUser' rather than simply 'target'.
This will help avoid confusion when we add support for the filesystem
keyring, since then the Mount will also be a "target".

Rename some variables from 'target' to 'targetUser'

---

README.md

For some time now, fscrypt actually does re-wrap a user's login
protector when their login passphrase changes, provided that the PAM
configuration is correct.  Remove the obsolete paragraph.
Update https://github.com/google/fscrypt/issues/51

README.md: remove obsolete warning about changing login passphrase

---

README.md

Update the example output in the README to match reality.
Also make a few other updates to the examples to take into account that
'fscrypt purge' now drops caches by default, and that the root
filesystem doesn't need to support encryption if the encrypted
directories are being created on a different filesystem.
Resolves https://github.com/google/fscrypt/issues/62

README.md: update output to match reality

---

security/keyring.go

When userKeyringIDLookup() looks up a user keyring, it links it into the
process keyring to ensure that the process retains the "possessor
privileges" over the user keyring, then caches the user keyring's ID.
Unfortunately, this use of the process keyring randomly fails because Go
creates threads before even init() and main() are run, and then can run
code on them later.  Since the kernel doesn't create the process keyring
until userspace requests it and the process keyring is actually a
per-thread property that's only inherited by new threads, different
threads in a Go process may see different process keyrings.
Fix this by removing the user keyring cache, switching from the process
keyring to the thread keyring, and using LockOSThread() to pin the
goroutine to an OS thread while needed …

keyring: fix permission denied accessing user keyring

---

actions/recovery.go
actions/recovery_test.go
cmd/fscrypt/commands.go
crypto/key.go
crypto/rand.go

If a user re-installs their system (or otherwise loses the /.fscrypt
directory on the root filesystem) they also lose access to any login
passphrase-protected directories on other filesystems, unless additional
protectors were manually added.  This can be unexpected, as it may be
expected that the old login passphrase would still work.
We can't really fix this by storing a login protector on every
filesystem because:
- If a user were to have N login protectors, it would take them N times
longer to log in, as every login protector would need to be unlocked.
- If a user were to change their login passphrase while any external
volumes were unmounted, login protectors would get out of sync.
- It's preferable that an external volume isn't unlockable by itself
using only a login passphrase, as …

Automatically generate recovery passphrase when useful

---

filesystem/mountpoint.go
filesystem/path.go

canonicalizePath() is now only used by an error path in
getMountFromLink(), which we can make use getDeviceName() instead.

filesystem: remove canonicalizePath()

---

security/privileges.go

The workaround for Go versions before 1.10 was already removed by
commit 3022c1603d96 ("Ensure setting user privileges is reversible").

privileges.go: remove a stale comment

---

README.md
cmd/fscrypt/setup.go

When 'fscrypt setup' sees that /etc/fscrypt.conf doesn't exist, don't
ask for confirmation before creating it.  Just do it.  This is the
normal use, and there's not a good reason to ask the user to confirm it.

cmd/fscrypt/setup: don't prompt to create /etc/fscrypt.conf

---

cmd/fscrypt/errors.go

When an fscrypt command fails and prints an error message, in some cases
it isn't clear that the message is actually an error, e.g.:
fscrypt encrypt: login protectors do not need a name
Make it clear by always prefixing the message with "[ERROR] ", e.g.
[ERROR] fscrypt encrypt: login protectors do not need a name
Update https://github.com/google/fscrypt/issues/186

cmd/fscrypt/errors: explicitly mark error messages as errors

---

actions/policy.go
actions/recovery.go
cmd/fscrypt/commands.go
filesystem/filesystem.go
filesystem/filesystem_test.go

Ensure that new policies and protectors always get deleted if `fscrypt encrypt` fails partway through.
Update https://github.com/google/fscrypt/issues/186

Clean up policies and protectors on error

---

cmd/fscrypt/commands.go
cmd/fscrypt/flags.go

While it's important to generate a recovery passphrase in the linked protector case to avoid data loss if the system is reinstalled, some people really don't want it (even though it can be safely ignored as it almost certainly has far more entropy than the login passphrase).
As a compromise, prompt for y/n before generating it, with default y.  Also, to allow disabling the recovery passphrase during noninteractive use, add a --no-recovery command-line option.
Update https://github.com/google/fscrypt/issues/186

cmd/fscrypt/commands: allow disabling recovery passphrase

---

Makefile

DESTDIR has a well established purpose
https://www.gnu.org/prep/standards/html_node/DESTDIR.html
It is a suffix for all the files to be installed. And it is used by
package managers who installs the files into some $tmpdir before
creating a package.
Change the build commands to follow this convention.
Add BINDIR that does the same what previous did $DESTDIR.

Use DESTDIR for install prefix

---

Makefile

Improve the documentation for the installation-related Makefile
variables, and update the commands to remove the forward slash after
$(DESTDIR) in order to remove a duplicate forward slash and match the
recommended usage.

Makefile: clean up installation commands

---

Makefile
cmd/fscrypt/flags.go
cmd/fscrypt/fscrypt.go
cmd/fscrypt/strings.go

There's no need to include the build time, author, and copyright info
in the output of "fscrypt --version". This information is:
- Overly complex (the current string is hard to parse)
- Inaccurate (there are other authors than just me)
- Unnecessary (the Apache 2 license is for Source Code)
- Makes reproducible builds impossible (fixes #206)
The default version string is just fine.

cmd: Simplify "fscrypt --version" output

---

Makefile

Passing -trimpath makes the build entirely reproducible. See #206 
Running `make` on two different computers (both Arch Linux, `go1.14.1`) gives a `sha256sum` of:
```
e6874f16445f7130cb1f7db63fb50850804f49d9b35af25e0a0f89b091f09ab7  ./bin/fscrypt
```

Makefile: Use trimpath if avalible

---

filesystem/filesystem.go
filesystem/mountpoint.go
filesystem/mountpoint_test.go

Update the /proc/self/mountinfo parsing code to allow selecting a Mount
with Subtree != "/", i.e. a Mount not of the full filesystem.  This is
needed to allow fscrypt to work in containers, where the root of the
filesystem may not be mounted.
See findMainMount() for details about the algorithm used.
Resolves https://github.com/google/fscrypt/issues/211

Allow fscrypt to work in containers

---

.travis.yml

There's no longer a need to override the Ubuntu version that the
Travis CI builds install e2fsprogs from, since we now use
"dist: bionic", and e2fsprogs in Bionic supports encryption.

travis.yml: stop overriding e2fsprogs version

---

actions/policy.go
cli-tests/t_v1_policy.out
cli-tests/t_v1_policy.sh
cmd/fscrypt/commands.go
cmd/fscrypt/status.go
keyring/keyring.go
keyring/user_keyring.go

'fscrypt lock' on a v1-encrypted directory doesn't warn about in-use
files, as the kernel doesn't provide a way to easily detect it.
Instead, implement a heuristic where we check whether a subdirectory can
be created.  If yes, then the directory must not be fully locked.
Make both 'fscrypt lock' and 'fscrypt status' use this heuristic.
Resolves https://github.com/google/fscrypt/issues/215

Try to detect incomplete locking of v1-encrypted directory

---

README.md

Explicitly mention that "fscrypt" here means the userspace tool, not the
kernel part.  Also write `fscrypt` in code font to emphasize this.

README.md: try to disambiguate "fscrypt"

---

cli-tests/t_encrypt.out
cli-tests/t_encrypt.sh
cmd/fscrypt/errors.go

Use %q, in case the paths contain whitespace.  Also clean the directory
path to remove trailing slashes before appending the ".new" suffix.

cmd/fscrypt: fix up path formatting in ErrDirNotEmpty suggestion

---

.travis.yml
cmd/fscrypt/errors.go

statfs.Bsize actually has platform-dependent type, despite the Go
documentation listing it as int64.
Resolves https://github.com/google/fscrypt/issues/233

cmd/fscrypt: fix 32-bit build

---

README.md

Ubuntu's PAM configuration framework only recognizes files in /usr, not
/usr/local.  So for installs from source, unfortunately we have to
recommend installing to /usr, despite this not being conventional.
Resolves https://github.com/google/fscrypt/issues/240

README.md: recommend 'sudo make install PREFIX=/usr' on Ubuntu

---

cmd/fscrypt/commands.go

Hi, 
I've fixed a bug related issue #242,

Fix nil error issue

---

cmd/fscrypt/commands.go

On an "incompletely locked" directory, isDirUnlockedHeuristic() is
supposed to return true, but on Linux v5.10-rc1 and later it returns
false since now creating a subdirectory fails rather than succeeds.
This change was intentional, so make isDirUnlockedHeuristic() apply a
second heuristic too: also return true if any filenames in the directory
don't appear to be valid no-key names.
This fixes cli-tests/t_v1_encrypt on Linux v5.10-rc1 and later.

cmd/fscrypt: fix isDirUnlockedHeuristic() on latest kernels

---

.travis.yml
cli-tests/common.sh
cmd/fscrypt/keys.go

Now that Travis CI supports a version of Ubuntu that has a kernel that
supports v2 encryption policies, upgrade to it and enable the cli tests.

travis.yml: upgrade to Ubuntu 20.04 and enable cli tests

---

Makefile
cmd/fscrypt/fscrypt_bash_completion

bash-completion: add completion script

---

cmd/fscrypt/prompt.go

This is the bugette mentioned in #272 - the format specifiers were never being filled in.
Also add a newline so the prompt to select a protector shows on a separate line.

cmd/fscrypt: fix missing protector error format

---

.github/workflows/ci.yml

In GitHub Workflows, apparently running 'apt-get update' before 'apt-get
install' is sometimes needed, and it doesn't hurt to always do it.

ci.yml: always run apt-get update

---

pam_fscrypt/config

Services launched by systemd user sessions on Debian / Ubuntu systems are often not able to access the home directory, because there is no guarantee / requirement that pam_fscrypt is sequenced before pam_systemd. Although this pam-config mechanism is Debian-specific, the config file is provided here upstream and unmodified in Debian. Raising the priority here so that it's always ordered ahead of pam_systemd will solve issues such as https://github.com/google/fscrypt/issues/270, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964951 and https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1889416.

pam_fscrypt/config: prioritise over other session modules

---

README.md
pam_fscrypt/config
pam_fscrypt/pam_fscrypt.go

* Make `pam_fscrypt` decide automatically whether dropping caches is needed, so that the "drop_caches" option is no longer needed.
* Make `pam_fscrypt` lock directories by default, so that the "lock_policies" option is no longer needed.  As there is a chance that a small number of users might want the previous default behavior of unlock-only, add an option "unlock_only" to get that behavior.
* Fix some things in the README related to `pam_fscrypt`.

pam_fscrypt: eliminate unnecessary options and improve documentation

---

.github/workflows/ci.yml
README.md

This is currently broken, and we don't really use the findings.

Stop generating and uploading coverage in CI

---

Makefile

This allows non Ubuntu distributions to opt out from the installation of Ubuntu-specific PAM files.

Makefile: Optionally avoid installation of Ubuntu-specific PAM config

---

cmd/fscrypt/format.go
cmd/fscrypt/keys.go
go.mod
go.sum

The `golang.org/x/crypto/ssh/terminal` package is deprecated and merely a
wrapper around `golang.org/x/term`. Thus, use the latter directly.

cmd/fscrypt: use golang.org/x/term

---

cmd/fscrypt/commands.go

Fix word mismatch in usage and description of metadata create policy
command.

cmd/fscrypt: fix word mismatch "protector" => "policy"

---

Makefile

When building pam_fscrypt.so, specify -buildmode=c-shared after
$(GO_FLAGS) so that it overrides any user-specified buildmode.
This is needed to allow -buildmode=pie to be specified in GO_FLAGS if
the packager wants to build fscrypt as a position-independent executable
(e.g. following https://wiki.archlinux.org/title/Go_package_guidelines).
Previously, trying to do this caused pam_fscrypt.so to be incorrectly
built as an executable rather than as a shared library.

Specify -buildmode=c-shared after GO_FLAGS rather than before

---

filesystem/path_test.go

Root can read all files, so this test fails when running as root.
Skip it instead.
Resolves https://github.com/google/fscrypt/issues/288

filesystem: skip TestHaveReadAccessTo() when running as root

---

actions/config.go

Running `crypto.PassphraseHash` in a loop allocates a lot of memory.
Golang is not always prudent about collecting the garbage from previous
runs, resulting in a OOM error on memory-pressured systems.
With a `maxMemoryBytes` of 128 MiB, this change reduces the maximum
resident memory for `fscrypt setup` to 141 MiB (was perviously 405 MiB)
Fixes #291

Only use 1/8 of the system RAM and run the Garbage Collector in the timing loop

---

README.md

Rename the troubleshooting section "Can't log in with ssh even when user's encrypted home directory is unlocked" to the more general "Some processes can't access unlocked encrypted files", and rewrite it to provide clearer directions for how to fix the problem by upgrading encrypted directories to policy version 2.
Also add a related section "Users can access other users' unlocked encrypted files" which covers the reverse "issue", i.e. people expecting some processes to *not* be able to access unlocked encrypted files.
Fixes https://github.com/google/fscrypt/issues/248

 README: improve troubleshooting tips for unlocked encrypted files

---

cmd/fscrypt/errors.go

Fix the GRUB detection logic to take into account that
MOUNTPOINT/boot/grub might not be on the same filesystem as MOUNTPOINT,
due to MOUNTPOINT/boot being another mountpoint.  The warning is only
appropriate when GRUB is installed on the same filesystem that
encryption is going to be enabled on.

cmd/fscrypt: fix detection of GRUB installation

---

cli-tests/common.sh

These confuse the latest version of shellcheck into thinking that
functions which take no arguments actually take arguments, which
triggers a bunch of warnings like "Use func "$@" if function's $1 should
mean script's $1", which causes 'make lint' to fail.  These checks
aren't too useful, so just remove them.

cli-tests/common.sh: remove argument count checks

---

cmd/fscrypt/commands.go

In Linux 5.15, the no-key name format is changing again; see
https://git.kernel.org/linus/ba47b515f5940603.  isPossibleNoKeyName()
sometimes doesn't recognize the new no-key names.  Update it accordingly
to recognize all possible no-key names.
Note: isPossibleNoKeyName() is only used as a heuristic to check whether
a v1-encrypted directory is incompletely locked or not.  Therefore, it's
not too important whether it works.  However, this change is needed for
cli-tests/t_v1_policy to pass.

cmd/fscrypt: recognize no-key names containing hyphen

---

README.md
actions/recovery.go
actions/recovery_test.go
cli-tests/t_encrypt_login.out
cli-tests/t_encrypt_login.sh
cmd/fscrypt/commands.go
cmd/fscrypt/flags.go
cmd/fscrypt/format.go

As per the feedback at https://github.com/google/fscrypt/issues/115
where users didn't understand that the recovery passphrase is important,
restore the original behavior where recovery passphrase generation
happens automatically without a prompt.  This applies to the case where
'fscrypt encrypt' is using a login protector on a non-root filesystem.
However, leave the --no-recovery option so that the recovery passphrase
can still be disabled if the user really wants to.  Also, clarify the
information provided about the recovery passphrase.
Update https://github.com/google/fscrypt/issues/115

Adjust recovery passphrase generation

---

README.md

Update https://github.com/google/fscrypt/issues/321
Update https://github.com/google/fscrypt/issues/324

README: document issue with ssh ChallengeResponseAuthentication

---

cli-tests/t_encrypt_login.out
cli-tests/t_encrypt_login.sh
filesystem/filesystem.go
util/util.go

When the root user creates a login protector for a non-root user, make
sure to chown() the protector file to make it owned by the user.
Without this, the protector cannot be updated by the user, which causes
it to get out of sync if the user changes their login passphrase.
Fixes https://github.com/google/fscrypt/issues/319

Set owner of login protectors to correct user

---

cli-tests/t_not_supported.out
cli-tests/t_not_supported.sh
filesystem/filesystem.go
filesystem/filesystem_test.go

Forbid 'fscrypt setup' on filesystems that aren't expected to support
encryption (other than the root filesystem), and skip looking for
fscrypt metadata directories on such filesystems.  This has two
benefits.  First, it avoids the printing of annoying warnings like:
pam_fscrypt[75038]: stat /run/user/0/.fscrypt: permission denied
pam_fscrypt[75038]: stat /run/user/0/.fscrypt/policies: permission denied
pam_fscrypt[75038]: stat /run/user/0/.fscrypt/protectors: permission denied
pam_fscrypt[75038]: stat /sys/firmware/efi/efivars/.fscrypt: invalid argument
pam_fscrypt[75038]: stat /sys/firmware/efi/efivars/.fscrypt/policies: invalid argument
pam_fscrypt[75038]: stat /sys/firmware/efi/efivars/.fscrypt/protectors: invalid argument
pam_fscrypt[75038]: stat /sys/fs/pstore/.fscrypt: permission …

filesystem: avoid accessing irrelevant filesystems

---

pam/pam.c
pam/pam.go
pam/pam.h
pam_fscrypt/pam_fscrypt.go

If someone runs 'passwd USER' as root, the user is assigned a new login
passphrase without their fscrypt login protector being updated.  Detect
this case and show a warning message using pam_info().
Fixes https://github.com/google/fscrypt/issues/273

pam_fscrypt: warn user if OLDAUTHTOK not given in chauthtok

---

actions/context_test.go

This fixes a test failure in the case where test.conf gets left over.

context_text: remove pre-existing test.conf

---

actions/policy.go
actions/policy_test.go
cli-tests/common.sh
cli-tests/t_change_passphrase.sh
cli-tests/t_encrypt_login.sh
cli-tests/t_metadata.out
cli-tests/t_metadata.sh
cmd/fscrypt/commands.go

Make remove-protector-from-policy work even if the protector cannot be
loaded (for example, due to having been deleted already).
Fixes https://github.com/google/fscrypt/issues/258
Fixes https://github.com/google/fscrypt/issues/272

cmd/fscrypt: don't load protector in remove-protector-from-policy

---

cli-tests/t_encrypt_login.out
cli-tests/t_encrypt_login.sh
filesystem/filesystem.go
filesystem/mountpoint.go
filesystem/mountpoint_test.go

Currently, linked protectors use filesystem link files of the form
"UUID=\<uuid\>".  These links get broken if the filesystem's UUID changes,
e.g. due to the filesystem being re-created even if the ".fscrypt"
directory is backed up and restored.
To prevent links from being broken (in most cases), start storing the
mountpoint path in the link files too, in the form
"UUID=\<uuid\>\nPATH=\<path\>\n".  When following a link, try the UUID
first, and if it doesn't work try the PATH.  While it's possible that
the path changed too, for login protectors (the usual use case of linked
protectors) this won't be an issue as the path will always be "/".
An alternative solution would be to fall back to scanning all
filesystems for the needed protector descriptor.  I decided not to do
that, since relying …

filesystem: store mountpoint in link files as a fallback

---

.github/workflows/ci.yml
Makefile
README.md
go.mod

Bump up the required Go version to 1.16 so that we can assume that Go
modules are enabled by default.  Go 1.16 is the latest end-of-life
release, so this makes it so that we support the latest end-of-life
release (1.16), the current maintainance release (1.17), the current
release (1.18), and future releases.  This the same approach we took
when we last bumped up the required Go version.
Also update the ci.yml file to test with these versions.

Bump up required Go version to 1.16

---

pam/pam.go
pam_fscrypt/pam_fscrypt.go

Update https://github.com/google/fscrypt/issues/350

Try to detect process being forked during PAM transaction

---

cli-tests/run.sh
cli-tests/t_v1_policy.sh
cli-tests/t_v1_policy_fs_keyring.sh

Annoyingly, for JSON formatting protojson randomly selects a spacing method (one space or two spaces) depending on a hash of some sections of the Go binary, to discourage depending on its output being stable.  This breaks some checks in the CLI tests of the contents of fscrypt.conf and the output of 'fscrypt status'.  As there doesn't appear to be a straightforward alternative currently, for now just update the tests to take into consideration the possible extra space.

cli-tests: account for protojson whitespace randomization

---

metadata/policy.go
metadata/policy_test.go

Split policyIoctl into setPolicyIoctl and getPolicyIoctl. Add a
os.Sync() call to setPolicyIoctl.
Policy ioctls are not necessary durable on return. For example, on
ext4 (ref: fs/ext4/crypto.c: ext4_set_context) they are not. This may
lead to a filesystem containing fscrypt metadata (in .fscrypt), but
without the policy applied on an encrypted directory.
Example:
Snapshotting a mounted ext4 filesystem on Ceph RBD right after
setting the policy. While subject to timing, with high probability the
snapshot will not have the policy set. Calling fsync fixes this.
Signed-off-by: Marcel Lauhoff <marcel.lauhoff@suse.com>

fsync set policy ioctls

---

metadata/config_test.go

Follow up to #362
Protojson randomly inserts whitespace to indicate that the output is
unstable, breaking out tests. To fix this, compact the output before
comparison.

Ignore JSON whitespace in tests

---

README.md
pam_fscrypt/pam_fscrypt.go

Now that it's been requested by users, bring back the "unlock_only" option, which was originally proposed as part of
https://github.com/google/fscrypt/pull/281 but was dropped in the final version of that pull request.
Resolves https://github.com/google/fscrypt/issues/357

Make pam_fscrypt.so support the unlock_only option

---

actions/config_test.go
actions/hashing_test.go
actions/recovery_test.go
cmd/fscrypt/fscrypt.go
filesystem/filesystem.go
filesystem/filesystem_test.go
filesystem/mountpoint.go
filesystem/mountpoint_test.go
filesystem/path_test.go
metadata/config.go
pam_fscrypt/run_fscrypt.go

Since Go 1.16 (which recently became the minimum supported Go version for this project), the package io/ioutil is deprecated in favor of equivalent functionality in the io and os packages.  staticcheck warns about this.  Address all the warnings by switching to the non-deprecated replacement functions.

Stop using deprecated package io/ioutil

---

actions/context.go
cmd/fscrypt/format.go
crypto/crypto.go
crypto/crypto_test.go
crypto/rand.go
filesystem/filesystem.go
filesystem/mountpoint.go
filesystem/mountpoint_test.go
metadata/config.go
pam/login.go
pam_fscrypt/pam_fscrypt.go
security/privileges.go

Probably resolves https://github.com/google/fscrypt/issues/382

mountpoint_test: skip TestLoadSourceDevice if loop0 doesn't exist

---

README.md

With the latest version of go, the recommended 'go get' commands fail:
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
Replace them with commands that work.

README.md: don't recommend 'go get'

---

Makefile

golint is not supported anymore.  See
https://github.com/golang/go/issues/38968.
We already use both 'go vet' and 'staticheck' which are maintained.

Stop using golang.org/x/lint

---

cli-tests/t_lock.out
cli-tests/t_lock.sh
cmd/fscrypt/errors.go
metadata/policy.go

Since opening an encrypted regular file that is locked fails with ENOKEY, getting the encryption policy of such a file is not possible. As a result, 'fscrypt status' and 'fscrypt lock' fail on such files. Provide a better error message that tries to explain what is going on.
Resolves https://github.com/google/fscrypt/issues/393

Provide better error message when given a locked regular file

---

.github/workflows/ci.yml

This addresses the following warning from GitHub Actions:
Node.js 16 actions are deprecated. Please update the following
actions to use Node.js 20: actions/checkout@v3. For more information
see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
A near-identical warning forced everyone to upgrade to v3 last year, so this is some pointless churn, but let's just get it over with again...

ci.yml: use actions/checkout@v4

---

README.md

Including a link to the specific report can help a reader recognize when the warning about systemd-homed is no longer important.
It might also help to drive attention to the right place to improve systemd-homed.

README.md: link to RFE about systemd-homed fscrypt version support

---

actions/policy.go
filesystem/mountpoint_test.go

This has to be since the mounts are reloaded each time a mount is added. 
In case of two mounts mounting at the same time there will be a race condition for applying policy.
I added the unit test in mountpoint for my sanity while developing and some kind of documentation of the issue.
This fixes issue #411

Compare mount by value instead of reference

---

cmd/fscrypt/flags.go

Document the logic described in `makeRawKey`.

Document stdin behaviour for getting raw key

---

cmd/fscrypt/commands.go

Do not pass a path as the format string argument to errors.Wrapf(), as this causes it to be misinterpreted as a format string, causing an unexpected message if the path contains something like '%s'.  Instead use errors.Wrap().  This was diagnosed by Go 1.24.
Fixes https://github.com/google/fscrypt/issues/422

Fix non-constant format string passed to errors.Wrapf()

---

.github/workflows/ci.yml

GitHub Actions will drop support for ubuntu-20.04 soon.

ci.yml: upgrade ubuntu-20.04 to ubuntu-latest
