cmd/fscrypt/commands.go, vendor/vendor.json
Fixes a bug in `vendor.json` that included "fscrypt/<pkg>" packages.
Fixes #1 and fixes #2
=> Bug fixing for "fscrypt encrypt"

actions/context.go, actions/policy.go, actions/policy_test.go
=> Polices can now be directly unlocked with Protectors

Makefile
=> Makefile: Build version flag no longer needs repo

CONTRIBUTING.md
Also establishes procedure of contacting myself and @tyhicks regarding significant security issues.
Closes #5
=> Update CONTRIBUTING.md to explain how issues will work

CONTRIBUTING.md, Makefile, README.md, cmd/fscrypt/errors.go, cmd/fscrypt/fscrypt.go, crypto/crypto.go, crypto/crypto_test.go, crypto/key.go, pam_fscrypt/pam_fscrypt.go
Fixes #45 
Fixes #38 
Fixes #13 
Various typos reverted (closes #43)
=> Fix a wide variety of small issues and update documentation

.gitignore, CONTRIBUTING.md, Makefile, actions/context.go, actions/context_test.go, actions/policy.go, actions/protector.go, cmd/fscrypt/commands.go, cmd/fscrypt/errors.go, cmd/fscrypt/flags.go, cmd/fscrypt/fscrypt.go, cmd/fscrypt/prompt.go, cmd/fscrypt/protector.go, cmd/fscrypt/setup.go, cmd/fscrypt/status.go, crypto/crypto_test.go, crypto/key.go, pam/pam.go, pam_fscrypt/pam_fscrypt.go, pam_fscrypt/run_fscrypt.go, pam_fscrypt/run_test.go, security/keyring.go, security/privileges.go, util/util.go
This PR creates a saner mechanism for querying and modifying keyrings. It also adds the `--user` flag which is described more in the help text.
Fixes #42 and Fixes #40
=> Changes to the keyrings interface, corresponding UI changes, and misc changes

CONTRIBUTING.md, README.md
PR #85 failed to update the documentation. This is now fixed with some
additional cleanup.
=> docs: Update CONTRIBUTING.md and README.md

.travis.yml
Key has scopes to the public repo. This allows it post releases
=> travis: Upload encrypted API key

.gitignore, CONTRIBUTING.md, Makefile, README.md, cmd/fscrypt/flags.go, filesystem/mountpoint.go, security/cache.go, security/keyring.go, security/privileges.go
* Remove spelling mistakes in the repository
* Add travis script to check for typos.
* Add command to Makefile to check for typos.
* Fixes #71
=> feat(spell-check): add make command for spell check.

.travis.yml, Makefile, pam/pam.c
=> Update Travis to use Ubuntu 18.04 and Go 1.12

cmd/fscrypt/commands.go
Resolves https://github.com/google/fscrypt/issues/132
=> cmd/fscrypt: give newly encrypted directories mode 0700

README.md
Resolves https://github.com/google/fscrypt/issues/58
=> README.md: improve documentation of GRUB limitation

README.md
Resolves https://github.com/google/fscrypt/issues/117
Resolves https://github.com/google/fscrypt/issues/127
=> README.md: improve documentation for kernel and filesystem support

README.md
Resolves https://github.com/google/fscrypt/issues/124
=> README.md: improve documentation for moving files into encrypted dirs

Makefile, go.mod
Also add `go` version attribute to `go.mod`.
Fixes #143
=> Prepare v0.2.5

cmd/fscrypt/format.go
Preserve empty lines rather than squashing them into a single space.
This allows having command descriptions that contain multiple
paragraphs.  This also eliminates the need to have a special case for
ordered lists.
=> cmd/fscrypt: preserve paragraphs in wrapText()

README.md
This is split off from https://github.com/google/fscrypt/pull/148
=> README.md: document /etc/fscrypt.conf

README.md
Resolves https://github.com/google/fscrypt/issues/181
=> Document how to check for kernel config options

actions/recovery.go
If the login protector was just created by the same 'fscrypt encrypt'
command, then policy.Context.Config.Source will be pam_passphrase.  This
needs to be overridden to custom_passphrase when creating the protector
for the recovery passphrase.
This fixes the following error:
fscrypt encrypt: login protectors do not need a name
Resolves https://github.com/google/fscrypt/issues/187
=> actions/recovery: ensure recovery passphrase is really custom_passphrase

.travis.yml, Makefile
=> Release version v0.2.6

Makefile
=> Release version v0.2.7

README.md
Update https://github.com/google/fscrypt/issues/220
=> README.md: improve documentation for login protectors

README.md
Update https://github.com/google/fscrypt/issues/220
=> README.md: fix typo "nrounds" => "rounds"

cli-tests/t_encrypt_login.out, cmd/fscrypt/protector.go
Update https://github.com/google/fscrypt/issues/220
=> cmd/fscrypt: link to guide when interactively creating login protector

README.md
Workflow names are case-sensitive
=> README: Fix badge image

README.md
Update https://github.com/google/fscrypt/issues/273
=> README: improve troubleshooting section for login protector not in sync

README.md
Fixes https://github.com/google/fscrypt/issues/194
Update https://github.com/google/fscrypt/issues/100
=> README: add troubleshooting section for keyring linkage issue

README.md
Inspired by https://reddit.com/r/linuxquestions/comments/n75dv4
=> README: add troubleshooting section for ENOPKG error

cli-tests/run.sh
=> cli-tests: fix failure with latest bash version

README.md
* README: documentation tweaks
* README: document symlink size bug
=> Updates to the troubleshooting documentation

README.md
Update https://github.com/google/fscrypt/issues/115
=> README: clarify how restoring /.fscrypt directory works

README.md
Resolves https://github.com/google/fscrypt/issues/305
=> README: mention LTS kernel versions with symlink bug fix

cli-tests/t_encrypt_raw_key.out, cli-tests/t_encrypt_raw_key.sh, cmd/fscrypt/keys.go
=> cmd/fscrypt: read key from stdin in non-interactive shell

README.md, cmd/fscrypt/strings.go
Fixes https://github.com/google/fscrypt/issues/318
=> README: elaborate on alternatives and threat model

cli-tests/t_encrypt_login.sh
I'm not sure how this passed the GitHub checks.
=> cli-tests: fix broken test

pam_fscrypt/pam_fscrypt.go, pam_fscrypt/run_fscrypt.go
If a session is opened for a user twice and the second doesn't have the AUTHTOK data, pam_fscrypt prints an error message that says it failed to unlock a protector because AUTHTOK data is missing.  This is misleading because the protector and its associated policies were already unlocked by the first session.
To avoid this, move the check for whether the policy is provisioned or not into policiesUsingProtector().  Also do the same for CloseSession.
=> pam_fscrypt: filter out irrelevant policies earlier

filesystem/mountpoint.go
This hopefully resolves https://github.com/google/fscrypt/issues/382.
=> filesystem/mountpoint: fall back to using mount source field
